"""added notifications

Revision ID: 1128d3e6e269
Revises: f703f911d4ae
Create Date: 2018-09-09 03:50:46.625141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1128d3e6e269'
down_revision = 'f703f911d4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nyaa_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('text', mysql.TEXT(collation='utf8mb4_bin'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sukebei_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('text', mysql.TEXT(collation='utf8mb4_bin'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nyaa_notification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    # sqlalchemy_utils.types.choice.ChoiceType()
    sa.Column('event_type', sa.SmallInteger(), nullable=False),
    sa.Column('notifier_id', sa.Integer(), nullable=False),
    sa.Column('notified_id', sa.Integer(), nullable=False),
    sa.Column('torrent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notified_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['notifier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['torrent_id'], ['nyaa_torrents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sukebei_notification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    # sqlalchemy_utils.types.choice.ChoiceType()
    sa.Column('event_type', sa.SmallInteger(), nullable=False),
    sa.Column('notifier_id', sa.Integer(), nullable=False),
    sa.Column('notified_id', sa.Integer(), nullable=False),
    sa.Column('torrent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notified_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['notifier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['torrent_id'], ['sukebei_torrents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sukebei_notification_events')
    op.drop_table('nyaa_notification_events')
    op.drop_table('sukebei_notifications')
    op.drop_table('nyaa_notifications')
    # ### end Alembic commands ###
